eureka:
  client:
    serviceUrl:
      defaultZone: http://@eureka.server.host@:@eureka.server.port@/eureka

server:
  port: @eureka.service.feign.port@

spring:
  application:
    name: @eureka.service.feign.name@


services:
  service-01:
    name: @eureka.service.01.name@
