server:
  port: @eureka.service.config.server.port@

spring:
  application:
    name: @eureka.service.config.server.name@
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/cwowhappy/study-spring-cloud
          searchPaths: profiles
