server:
  port: @eureka.service.config.server.port@

eureka:
  client:
    serviceUrl:
      defaultZone: http://@eureka.server.host@:@eureka.server.port@/eureka

spring:
  application:
    name: @eureka.service.config.server.name@
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/cwowhappy/study-spring-cloud/
          searchPaths: profiles
