server:
  port: 8080

spring:
  application:
    name: user-management
  datasource:
    schema: classpath:database/schema.sql
    data: classpath:database/data.sql
    druid:
      driver-class-name: @database.driver@
      url: @database.url@
      username: @database.username@
      password: @database.password@
      initalSize: 2
      minIdle: 2
      maxActive: 5
      maxWait: 30000
      testWhileIdle: false
      aop-pattern: com.cwowhappy.service.user.service
      web-stat-filter:
        enable: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico"
      stat-view-servlet:
        enable: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: 123456
      filter:
        stat:
          db-type: h2
          log-show-sql: true
          slow-sql-millis: 2000
        wall:
          enable: true
          db-type: h2
          config:
            delete-allow: false
            drop-table-allow: false

mybatis:
  config-location: classpath:mybatis-config.xml

logging:
  level:
    root: INFO