eureka:
  client:
    serviceUrl:
      defaultZone: http://@eureka.server.host@:@eureka.server.port@/eureka

server:
  port: @eureka.service.zuul.port@

spring:
  application:
    name: @eureka.service.zuul.name@

zuul:
  routes:
    feign:
      path: /feign/**
      serviceId: @eureka.service.feign.name@
    ribbon:
      path: /ribbon/**
      serviceId: @eureka.service.ribbon.name@