eureka:
  client:
    serviceUrl:
      defaultZone: http://@eureka.server.host@:@eureka.server.port@/eureka

server:
  port: @service.port@

spring:
  application:
    name: @eureka.service.01.name@
